version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:14.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
